
name: CI Pipeline 


on:
  push:
    branches:
      -main


jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name  : checkout code 
      users: action/checkout@v3

    - name : Setup Node.js
      users: action/Setup-node@v3

    - name: install dependencies
      run: npm install

    - name: Run Tests
      run: npm test



